---
# defaults file;
# zabbix role specific

zabbix_server_version: 5.2
zabbix_version: "{{ zabbix_server_version }}"
zabbix_repo: zabbix

zabbix_server_apt_priority:
zabbix_server_package_state: present
zabbix_server_install_recommends: True
zabbix_server_install_database_client: True
zabbix_server_conf_mode: 0640

zabbix_service_state: started
zabbix_service_enabled: True
zabbix_repo_yum_schema: https
zabbix_repo_yum_disabled: "*"
zabbix_repo_yum_enabled: []
zabbix_repo_yum:
  - name: zabbix
    description: Zabbix Official Repository - $basearch
    baseurl: "{{ zabbix_repo_yum_schema }}://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/{{ ansible_distribution_major_version }}/$basearch/"
    gpgcheck: 0
    mode: '0644'
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX
    state: present
  - name: zabbix-non-supported
    description: Zabbix Official Repository non-supported - $basearch
    baseurl: "{{ zabbix_repo_yum_schema }}://repo.zabbix.com/non-supported/rhel/{{ ansible_distribution_major_version }}/$basearch/"
    mode: '0644'
    gpgcheck: 0
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX
    state: present

# User (EPEL specific)
zabbix_server_username: zabbix
zabbix_server_groupname: zabbix

# Database
zabbix_server_database: pgsql
zabbix_server_database_long: postgresql
zabbix_database_creation: True
zabbix_database_sqlload: True
zabbix_server_dbtlsconnect:
zabbix_server_dbtlscafile:
zabbix_server_dbtlscertfile:
zabbix_server_dbtlskeyfile:
zabbix_server_dbtlscipher:
zabbix_server_dbtlscipher13:

# zabbix-server specific vars
zabbix_server_listenport: 10051
zabbix_server_sourceip:
zabbix_server_logtype: file
zabbix_server_logfile: /var/log/zabbix/zabbix_server.log
zabbix_server_logfilesize: 10
zabbix_server_debuglevel: 3
zabbix_server_pidfile: /var/run/zabbix/zabbix_server.pid
zabbix_server_socketdir: /var/run/zabbix
zabbix_server_real_dbhost:
zabbix_server_dbhost: localhost
zabbix_server_dbname: zabbix-server
zabbix_server_dbencoding: utf8
zabbix_server_dbcollation: utf8_bin
zabbix_server_dbschema:
zabbix_server_dbuser: zabbix-server
zabbix_server_dbpassword: zabbix-server
zabbix_server_dbsocket:
zabbix_server_dbport: 5432
zabbix_server_dbhost_run_install: true
zabbix_server_privileged_host: localhost
zabbix_server_historystorageurl:
zabbix_server_historystoragetypes: uint,dbl,str,log,text
zabbix_server_historystoragedateindex: 0
zabbix_server_exportdir:
zabbix_server_exportfilesize: 1G
zabbix_server_startpollers: 5
zabbix_server_startipmipollers: 0
zabbix_server_startpollersunreachable: 1
zabbix_server_starttrappers: 5
zabbix_server_startpingers: 1
zabbix_server_startdiscoverers: 1
zabbix_server_starthttppollers: 1
zabbix_server_startpreprocessors: 3
zabbix_server_starttimers: 1
zabbix_server_javagateway:
zabbix_server_javagatewayport: 10052
zabbix_server_startjavapollers: 5
zabbix_server_startvmwarecollectors: 0
zabbix_server_vmwarefrequency: 60
zabbix_server_vmwarecachesize: 8M
zabbix_server_snmptrapperfile: /tmp/zabbix_traps.tmp
zabbix_server_startsnmptrapper: 0
zabbix_server_listenip:
zabbix_server_housekeepingfrequency: 1
zabbix_server_maxhousekeeperdelete: 500
zabbix_server_senderfrequency: 30
zabbix_server_cachesize: 8M
zabbix_server_cacheupdatefrequency: 60
zabbix_server_startdbsyncers: 4
zabbix_server_historycachesize: 8M
zabbix_server_historyindexcachesize: 4M
zabbix_server_trendcachesize: 4M
zabbix_server_historytextcachesize: 16M
zabbix_server_valuecachesize: 8M
zabbix_server_nodenoevents: 0
zabbix_server_nodenohistory: 0
zabbix_server_timeout: 3
zabbix_server_trappertimeout: 300
zabbix_server_unreachableperiod: 45
zabbix_server_unavailabledelay: 60
zabbix_server_unreachabledelay: 15
zabbix_server_alertscriptspath: /usr/lib/zabbix/alertscripts
zabbix_server_externalscriptspath: /usr/lib/zabbix/externalscripts
zabbix_server_fpinglocation: /usr/sbin/fping
zabbix_server_fping6location: /usr/sbin/fping6
zabbix_server_sshkeylocation:
zabbix_server_logslowqueries: 0
zabbix_server_tmpdir: /tmp
zabbix_server_startproxypollers: 1
zabbix_server_proxyconfigfrequency: 3600
zabbix_server_proxydatafrequency: 1
zabbix_server_allowroot: 0
zabbix_server_user: zabbix
zabbix_server_include: /etc/zabbix/zabbix_server.conf.d
zabbix_server_include_mode: '0755'
zabbix_server_sslcertlocation: ${datadir}/zabbix/ssl/certs
zabbix_server_sslkeylocation: ${datadir}/zabbix/ssl/keys
zabbix_server_sslcalocation:
zabbix_server_loadmodulepath: ${libdir}/modules
zabbix_server_loadmodule:
zabbix_server_tlscafile:
zabbix_server_tlscrlfile:
zabbix_server_tlscertfile:
zabbix_server_tlskeyfile:
zabbix_server_startescalators: 1
zabbix_server_vmwareperffrequency: 60
zabbix_server_vmwaretimeout: 10
zabbix_server_manage_service: True

# SELinux specific
zabbix_selinux: False
selinux_allow_zabbix_can_network: False
selinux_allow_zabbix_can_http: False
