---
# defaults file for zabbix-proxy

zabbix_proxy_version: 5.2
zabbix_version: "{{ zabbix_proxy_version }}"
zabbix_selinux: False

# These variables are optional. They specify the version of Zabbix proxy package.

# zabbix_proxy_rhel_version: 4.4.4
# zabbix_proxy_debian_version: 1:4.4.4-1+stretch
# zabbix_proxy_ubuntu_version: 1:4.4.4-1+xenial

zabbix_repo: zabbix
zabbix_proxy_apt_priority:
zabbix_proxy_package_state: present
zabbix_proxy_install_database_client: True
zabbix_install_pip_packages: true
zabbix_repo_yum_schema: https
zabbix_proxy_conf_mode: "0644"
zabbix_repo_yum_disabled: "*"
zabbix_repo_yum_enabled: []
zabbix_repo_yum:
  - name: zabbix
    description: Zabbix Official Repository - $basearch
    baseurl: "{{ zabbix_repo_yum_schema }}://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/{{ ansible_distribution_major_version }}/$basearch/"
    gpgcheck: 0
    mode: '0644'
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX
    state: present
  - name: zabbix-non-supported
    description: Zabbix Official Repository non-supported - $basearch
    baseurl: "{{ zabbix_repo_yum_schema }}://repo.zabbix.com/non-supported/rhel/{{ ansible_distribution_major_version }}/$basearch/"
    mode: '0644'
    gpgcheck: 0
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX
    state: present

# User (EPEL specific)
zabbix_proxy_username: zabbix
zabbix_proxy_groupname: zabbix

zabbix_server_host: 192.168.1.1
zabbix_server_port: 10051
zabbix_database_creation: True
zabbix_database_sqlload: True
zabbix_proxy_dbtlsconnect:
zabbix_proxy_dbtlscafile:
zabbix_proxy_dbtlscertfile:
zabbix_proxy_dbtlskeyfile:
zabbix_proxy_dbtlscipher:
zabbix_proxy_dbtlscipher13:

# Some role specific vars
zabbix_proxy_database: mysql
zabbix_proxy_database_long: mysql
# zabbix_proxy_database: pgsql
# zabbix_proxy_database_long: postgresql
# zabbix_proxy_database: sqlite3
# zabbix_proxy_database_long: sqlite3

# zabbix-proxy specifc vars
zabbix_proxy_mode: 0
zabbix_proxy_hostname: "{{ inventory_hostname }}"
zabbix_proxy_listenport: 10051
zabbix_proxy_sourceip:
zabbix_proxy_logfile: /var/log/zabbix/zabbix_proxy.log
zabbix_proxy_logfilesize: 10
zabbix_proxy_enableremotecommands: 0
zabbix_proxy_debuglevel: 3
zabbix_proxy_pidfile: /var/run/zabbix/zabbix_proxy.pid
zabbix_proxy_socketdir: /var/run/zabbix
zabbix_proxy_dbencoding: utf8
zabbix_proxy_dbcollation: utf8_bin
zabbix_proxy_dbhost: localhost
zabbix_proxy_dbname: zabbix_proxy
zabbix_proxy_dbschema:
zabbix_proxy_dbuser: zabbix_proxy
zabbix_proxy_dbpassword: zabbix_proxy
zabbix_proxy_dbsocket:
zabbix_proxy_dbport: 5432
zabbix_proxy_dbhost_run_install: true
zabbix_proxy_privileged_host: localhost
zabbix_proxy_localbuffer: 0
zabbix_proxy_offlinebuffer: 1
zabbix_proxy_heartbeatfrequency: 60
zabbix_proxy_configfrequency: 3600
zabbix_proxy_datasenderfrequency: 1
zabbix_proxy_startpollers: 5
zabbix_proxy_startipmipollers: 0
zabbix_proxy_startpollersunreachable: 1
zabbix_proxy_starttrappers: 5
zabbix_proxy_startpingers: 1
zabbix_proxy_startdiscoverers: 1
zabbix_proxy_starthttppollers: 1
zabbix_proxy_startpreprocessors: 3
zabbix_proxy_javagateway:
zabbix_proxy_javagatewayport: 10052
zabbix_proxy_startjavapollers: 5
zabbix_proxy_startvmwarecollector: 0
zabbix_proxy_vmwarefrequency: 60
zabbix_proxy_vmwarecachesize: 8
zabbix_proxy_snmptrapperfile: /tmp/zabbix_traps.tmp
zabbix_proxy_snmptrapper: 0
zabbix_proxy_listenip:
zabbix_proxy_housekeepingfrequency: 1
zabbix_proxy_cachesize: 8
zabbix_proxy_startdbsyncers: 4
zabbix_proxy_historycachesize: 8
zabbix_proxy_historyindexcachesize: 4
zabbix_proxy_historytextcachesize: 16
zabbix_proxy_timeout: 3
zabbix_proxy_trappertimeout: 300
zabbix_proxy_unreachableperiod: 45
zabbix_proxy_unavaliabledelay: 60
zabbix_proxy_unreachabedelay: 15
zabbix_proxy_externalscripts: /usr/lib/zabbix/externalscripts
zabbix_proxy_fpinglocation: /usr/sbin/fping
zabbix_proxy_fping6location: /usr/sbin/fping6
zabbix_proxy_sshkeylocation:
zabbix_proxy_loglowqueries: 0
zabbix_proxy_tmpdir: /tmp
zabbix_proxy_allowroot: 0
zabbix_proxy_include: /etc/zabbix/zabbix_proxy.conf.d
zabbix_proxy_include_mode: '0755'
zabbix_proxy_libdir: /usr/lib/zabbix
zabbix_proxy_loadmodulepath: "{{ zabbix_proxy_libdir }}/modules"
zabbix_proxy_manage_service: True

# TLS settings
zabbix_proxy_tlsconnect:
zabbix_proxy_tlsaccept:
zabbix_proxy_tlscafile:
zabbix_proxy_tlscrlfile:
zabbix_proxy_tlsservercertissuer:
zabbix_proxy_tlsservercertsubject:
zabbix_proxy_tlscertfile:
zabbix_proxy_tlskeyfile:
zabbix_proxy_tlspskidentity:

zabbix_proxy_tls_config:
  no_encryption: 'no_encryption'
  PSK: 'PSK'
  certificate: 'certificate'

# Zabbix API stuff
zabbix_url: "http://zabbix.dj-wasabi.local"
# zabbix_api_http_user: admin
# zabbix_api_http_password: admin
zabbix_api_user: Admin
zabbix_api_pass: zabbix
zabbix_api_create_proxy: False
zabbix_create_proxy: present  # or absent
zabbix_proxy_status: active   # or passive
zabbix_proxy: null
zabbix_useuip: 1
zabbix_proxy_become_on_localhost: True
zabbix_proxy_interface:
  useip: "{{ zabbix_useuip }}"
  ip: "{{ zabbix_proxy_ip }}"
  dns: "{{ ansible_fqdn }}"
  port: "{{ zabbix_proxy_listenport }}"
