zabbix_valid_proxy_versions:
  # Debian
  "12":
    - 6.4
    - 6.0
  "11":
    - 6.4
    - 6.2
    - 6.0
  "10":
    - 6.4
    - 6.2
    - 6.0
  "22":
    - 6.4
    - 6.2
    - 6.0
  "20":
    - 6.4
    - 6.2
    - 6.0
  "18":
    - 6.4
    - 6.2
    - 6.0

mysql_client_pkgs:
  # Debian
  "12":
    - default-mysql-client
    - "{{ zabbix_python_prefix }}-mysqldb"
  "11":
    - default-mysql-client
    - "{{ zabbix_python_prefix }}-mysqldb"
  "10":
    - mariadb-client
    - "{{ zabbix_python_prefix }}-mysqldb"
  # Ubuntu
  "22":
    - default-mysql-client
    - "{{ zabbix_python_prefix }}-mysqldb"
  "20":
    - default-mysql-client
    - "{{ zabbix_python_prefix }}-mysqldb"
  "18":
    - default-mysql-client
    - "{{ zabbix_python_prefix }}-mysqldb"

mysql_plugin:
  "18": mysql_native_password
  "10": mysql_native_password

debian_keyring_path: /etc/apt/keyrings/
zabbix_gpg_key: "{{ debian_keyring_path }}/zabbix-official-repo.asc"
_zabbix_repo_deb_url: "http://repo.zabbix.com/zabbix/{{ zabbix_proxy_version }}/{{ ansible_distribution.lower() }}"
