---

- include_tasks: apache.yml

- name: "RedHat | Install apache vhost"
  template:
    src: apache_vhost.conf.j2
    dest: /etc/httpd/conf.d/zabbix.conf
    owner: "{{ zabbix_web_conf_web_user }}"
    group: "{{ zabbix_web_conf_web_group }}"
    mode: 0644
  when: zabbix_vhost
  become: true
  notify:
    - restart apache
  tags:
    - zabbix-server
