---
- name: "Debian | Set PHP Dependencies"
  ansible.builtin.set_fact:
    zabbix_web_php_dependencies: "{{ _apache_php_dependencies if zabbix_web_http_server == 'apache' else _nginx_php_dependencies }}"
  tags:
    - config

- name: "Debian | Set some variables"
  ansible.builtin.set_fact:
    zabbix_short_version: "{{ zabbix_web_version | regex_replace('\\.', '') }}"
    zabbix_underscore_version: "{{ zabbix_web_version | regex_replace('\\.', '_') }}"
    zabbix_python_prefix: "python{% if ansible_python_version is version('3', '>=') %}3{% endif %}"
  tags:
    - always

- name: "Debian | Install PHP Dependencies"
  ansible.builtin.apt:
    pkg: "{{ zabbix_web_php_dependencies }}"
    state: "present"
    update_cache: true
    cache_valid_time: 0
  environment:
    http_proxy: "{{ zabbix_http_proxy | default(None) | default(omit) }}"
    https_proxy: "{{ zabbix_https_proxy | default(None) | default(omit) }}"
  register: zabbix_web_php_dependencies_install
  until: zabbix_web_php_dependencies_install is succeeded
  become: true
  tags:
    - install
    - dependencies

- name: "Debian | Install PgSQL Dependencies"
  ansible.builtin.apt:
    pkg: "php{{ zabbix_web_php_installed_version }}-pgsql"
    state: "present"
    update_cache: true
    cache_valid_time: 0
  environment:
    http_proxy: "{{ zabbix_http_proxy | default(None) | default(omit) }}"
    https_proxy: "{{ zabbix_https_proxy | default(None) | default(omit) }}"
  register: zabbix_web_php_dependencies_install
  until: zabbix_web_php_dependencies_install is succeeded
  become: true
  when: zabbix_server_database == 'pgsql'
  tags:
    - install
    - dependencies
    - database

# In releases older than Debian 12 and Ubuntu 22.04, /etc/apt/keyrings does not exist by default.
# It SHOULD be created with permissions 0755 if it is needed and does not already exist.
# See: https://wiki.debian.org/DebianRepository/UseThirdParty
- name: "Debian | Create /etc/apt/keyrings/ on older versions"
  ansible.builtin.file:
    path: /etc/apt/keyrings/
    state: directory
    mode: "0755"
  become: true
  when:
    - (ansible_distribution == "Ubuntu" and ansible_distribution_major_version < "22") or
      (ansible_distribution == "Debian" and ansible_distribution_major_version < "12")

- name: "Debian | Download gpg key"
  when: not ansible_check_mode  # Because get_url always has changed status in check_mode.
  ansible.builtin.get_url:
    url: "{{ zabbix_repo_deb_gpg_key_url }}"
    dest: "{{ zabbix_gpg_key }}"
    mode: "0644"
    force: true
  environment:
    http_proxy: "{{ zabbix_http_proxy | default(None) | default(omit) }}"
    https_proxy: "{{ zabbix_https_proxy | default(None) | default(omit) }}"
  become: true
  tags:
    - install

- name: "Debian | Installing repository {{ ansible_distribution }}"
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/zabbix.sources
    owner: root
    group: root
    mode: 0644
    content: |
      Types: deb{{ ' deb-src' if zabbix_repo_deb_include_deb_src }}
      Enabled: yes
      URIs: {{ zabbix_repo_deb_url }}
      Suites: {{ ansible_distribution_release }}
      Components: {{ zabbix_repo_deb_component }}
      Architectures: {{ 'amd64' if ansible_machine != 'aarch64' else 'arm64'}}
      Signed-By: {{ zabbix_gpg_key }}
  become: true
  tags:
    - install

- name: "Debian | Create /etc/apt/preferences.d/"
  ansible.builtin.file:
    path: /etc/apt/preferences.d/
    state: directory
    mode: "0755"
  when:
    - zabbix_web_apt_priority | int
  become: true
  tags:
    - install

- name: "Debian | Configuring the weight for APT"
  ansible.builtin.copy:
    dest: "/etc/apt/preferences.d/zabbix_server-{{ zabbix_proxy_database }}"
    content: |
      Package: zabbix_server-{{ zabbix_proxy_database }}
      Pin: origin repo.zabbix.com
      Pin-Priority: {{ zabbix_web_apt_priority }}
    owner: root
    mode: "0644"
  when:
    - zabbix_web_apt_priority | int
  become: true
  tags:
    - install

- name: "Debian | Install zabbix-web"
  ansible.builtin.apt:
    pkg: "zabbix-frontend-php"
    state: "{{ zabbix_web_package_state }}"
    update_cache: true
    cache_valid_time: 0
  environment:
    http_proxy: "{{ zabbix_http_proxy | default(None) | default(omit) }}"
    https_proxy: "{{ zabbix_https_proxy | default(None) | default(omit) }}"
  register: zabbix_web_package_install
  until: zabbix_web_package_install is succeeded
  become: true
  tags:
    - install

- name: "Debian | Link graphfont.ttf (workaround ZBX-10467)"
  ansible.builtin.file:
    src: "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
    path: "/usr/share/zabbix/fonts/graphfont.ttf"
    state: link
  become: true
  tags:
    - install
