---
- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - always

- name: Determine Latest Supported Zabbix Version
  set_fact:
    zabbix_web_version: "{{ zabbix_valid_web_versions[ansible_distribution_major_version][0] | default(6.2) }}"
  when: zabbix_web_version is not defined

- name: Set More Variables
  set_fact:
    zabbix_valid_version: "{{ zabbix_web_version|float in zabbix_valid_web_versions[ansible_distribution_major_version] }}"
    zabbix_db_type_long: "{{ 'postgresql' if zabbix_server_database == 'pgsql' else 'mysql' }}"

- name: Stopping Install of Invalid Version
  fail:
    msg: Zabbix version {{ zabbix_web_version }} is not supported on {{ ansible_distribution }} {{ ansible_distribution_major_version }}
  when: not zabbix_valid_version

- name: Determine PHP Version
  shell: php --version | head -1 | awk '{ print $2 }' | awk -F '.' '{print $1"."$2}'
  register: _zabbix_web_php_installed_version
  changed_when: false

- name: Set PHP Version
  set_fact:
    zabbix_web_php_installed_version: "{{ _zabbix_web_php_installed_version.stdout }}"

# - name: Set PHP Variables (Centos 7)
#   set_fact:
#     zabbix_php_fpm_listen: "{{ zabbix_php_fpm_listen if zabbix_php_fpm_listen is defined else '/var/opt/rh/rh-php72/run/php-fpm/zabbix.sock' }}"
#   when:
#     - ansible_os_family == "RedHat"
#     - ansible_distribution_major_version == '7'

- name: Set PHP Variables
  set_fact:
    zabbix_php_fpm_listen: "{{ zabbix_php_fpm_listen if zabbix_php_fpm_listen is defined else _zabbix_php_fpm_listen }}"
    zabbix_php_fpm_dir: "{{ zabbix_php_fpm_dir if zabbix_php_fpm_dir is defined else _php_fpm_dir }}"
    zabbix_php_fpm_session: "{{ zabbix_php_fpm_session if zabbix_php_fpm_session is defined else _php_fpm_session }}"

- name: Include OS Specific Tasks
  include_tasks: "{{ ansible_os_family }}.yml"

- name: "Install the web server specific tasks"
  include_tasks: "{{ zabbix_web_http_server }}.yml"
  tags:
    - zabbix-web

- name: "Create zabbix-web directory"
  file:
    path: /etc/zabbix/web
    owner: "{{ zabbix_web_user }}"
    group: "{{ zabbix_web_group }}"
    state: directory
    mode: 0755
  tags:
    - zabbix-web
    - init
    - config

- name: "Configure zabbix-web"
  template:
    src: zabbix.conf.php.j2
    dest: /etc/zabbix/web/zabbix.conf.php
    owner: "{{ zabbix_web_user }}"
    group: "{{ zabbix_web_group }}"
    mode: "{{ zabbix_web_conf_mode }}"
  notify:
    - "restart {{ zabbix_web_http_server }}"
  tags:
    - zabbix-web
    - init
    - config

- name: "Debian | Install PHP"
  template:
    src: php-fpm.conf.j2
    dest: "{{ zabbix_php_fpm_dir }}/zabbix.conf"
    owner: "{{ zabbix_web_user }}"
    group: "{{ zabbix_web_group }}"
    mode: 0644
  become: true
  when:
    - zabbix_vhost
    - ansible_os_family == "Debian"
  notify:
    - restart php-fpm-version
