---

- name: "SELinux | RedHat | Install related SELinux package"
  yum:
    name:
      - libsemanage-python
    state: present
  environment:
    http_proxy: "{{ zabbix_http_proxy | default(None) | default(omit) }}"
    https_proxy: "{{ zabbix_https_proxy | default(None) | default(omit) }}"
  register: zabbix_web_dependencies_installed
  until: zabbix_web_dependencies_installed is succeeded
  become: true
  when:
    - ansible_os_family == "RedHat"
    - selinux_allow_zabbix_can_network
    - ansible_distribution_major_version == "7" or ansible_distribution_major_version == "6"
  tags:
    - zabbix-web

- name: "SELinux | RedHat | Install related SELinux package on RHEL9 and RHEL8"
  yum:
    name:
      - python3-libsemanage
    state: present
  environment:
    http_proxy: "{{ zabbix_http_proxy | default(None) | default(omit) }}"
    https_proxy: "{{ zabbix_https_proxy | default(None) | default(omit) }}"
  register: zabbix_web_dependencies_installed
  until: zabbix_web_dependencies_installed is succeeded
  become: true
  when:
    - ansible_os_family == "RedHat"
    - selinux_allow_zabbix_can_network
    - ansible_distribution_major_version|int >= 8
  tags:
    - zabbix-web

- name: "SELinux | RedHat | Enable zabbix_can_network SELinux boolean"
  ansible.posix.seboolean:
    name: zabbix_can_network
    state: true
    persistent: true
  become: true
  when:
    - ansible_os_family == "RedHat"
    - selinux_allow_zabbix_can_network
  tags:
    - zabbix-web

- name: "SELinux | Allow httpd to connect to db (SELinux)"
  ansible.posix.seboolean:
    name: httpd_can_network_connect_db
    persistent: true
    state: true
  become: true
  when:
    - ansible_selinux.status == "enabled"
    - selinux_allow_zabbix_can_network
  tags: selinux

- name: "SELinux | Allow httpd to connect to zabbix (SELinux)"
  ansible.posix.seboolean:
    name: httpd_can_connect_zabbix
    persistent: true
    state: true
  become: true
  when:
    - ansible_selinux.status == "enabled"
    - selinux_allow_zabbix_can_network
  tags: selinux

- name: "SELinux | Allow httpd to connect to ldap (SELinux)"
  ansible.posix.seboolean:
    name: httpd_can_connect_ldap
    persistent: true
    state: true
  become: true
  when:
    - ansible_selinux.status == "enabled"
    - zabbix_apache_can_connect_ldap | bool
  tags: selinux
