---
# vars file for zabbix_agent (FreeBSD)

zabbix_agent_service: zabbix_agentd
zabbix_agent_conf: zabbix_agentd.conf

# No agent2 package for bsd
zabbix_agent2: false

zabbix_agent_package: "{{ _zabbix_agent_package_versions[zabbix_agent_version] }}"

zabbix_base_dir: "/usr/local/etc/{{ zabbix_agent_package | split('-') | first }}"
zabbix_agent_include: "{{ zabbix_base_dir }}/zabbix_agentd.conf.d"

zabbix_root_group: wheel

_zabbix_agent_tlspskfile: "{{ zabbix_base_dir }}/tls_psk_auto.secret"
_zabbix_agent_tlspskidentity_file: "{{ zabbix_base_dir }}/tls_psk_auto.identity"

zabbix_valid_agent_versions:
  "15":
    - 7.4
    - 7.2
    - 7.0
    - 6.0
  "14":
    - 7.4
    - 7.2
    - 7.0
    - 6.0
  "13":
    - 7.4
    - 7.2
    - 7.0
    - 6.0

_zabbix_agent_package_versions:
  "7.4": zabbix74-agent
  "7.2": zabbix72-agent
  "7.0": zabbix7-agent
  "6.0": zabbix6-agent
