---
# vars file for zabbix_agent (RedHat)

zabbix_agent: zabbix-agent

_zabbix_agent_package: "{{ zabbix_agent2 | ternary('zabbix-agent2', 'zabbix-agent') }}-{{ zabbix_agent_version }}.{{ zabbix_agent_version_minor }}"
_zabbix_agent_get_package: "zabbix-get-{{ zabbix_agent_version }}.{{ zabbix_agent_version_minor }}"
_zabbix_agent_sender_package: "zabbix-sender-{{ zabbix_agent_version }}.{{ zabbix_agent_version_minor }}"

_zabbix_agent_disable_repo:
  - epel

zabbix_valid_agent_versions:
  "10":
    - 7.4
  "9":
    - 7.4
    - 7.2
    - 7.0
    - 6.0
  "8":
    - 7.4
    - 7.2
    - 7.0
    - 6.0
