---
- name: "Debian | Include Zabbix gpg ids"
  include_vars: zabbix.yml
  tags:
    - always

- name: "Debian | Set some variables"
  set_fact:
    zabbix_short_version: "{{ zabbix_javagateway_version | regex_replace('\\.', '') }}"
  tags:
    - always

- name: "Debian | Set some variables"
  set_fact:
    zabbix_javagateway_apt_repository:
      - "http://repo.zabbix.com/zabbix/{{ zabbix_javagateway_version }}/{{ ansible_distribution.lower() }}/"
      - "{{ ansible_distribution_release }}"
      - "main"
  when:
    - ansible_machine != "aarch64"
  tags:
    - always

- name: "Debian | Set some variables"
  set_fact:
    zabbix_javagateway_apt_repository:
      - "http://repo.zabbix.com/zabbix/{{ zabbix_javagateway_version }}/{{ ansible_distribution.lower() }}-arm64/"
      - "{{ ansible_distribution_release }}"
      - "main"
  when:
    - ansible_machine == "aarch64"
  tags:
    - always

- name: "Debian | Install gpg key"
  apt_key:
    id: "{{ sign_keys[zabbix_short_version][ansible_distribution_release]['sign_key'] }}"
    url: http://repo.zabbix.com/zabbix-official-repo.key
  become: true
  tags:
    - install
    - repo

- name: "Debian | Installing repository Debian"
  apt_repository:
    repo: "{{ item }} {{ zabbix_javagateway_apt_repository | join(' ') }}"
    state: present
  become: true
  with_items:
    - deb-src
    - deb
  tags:
    - install
    - repo

- name: "Debian | Installing zabbix-java-gateway"
  apt:
    pkg: zabbix-java-gateway
    state: "{{ zabbix_javagateway_package_state }}"
    update_cache: true
    force: true
    cache_valid_time: 3600
  environment:
    http_proxy: "{{ zabbix_http_proxy | default(None) | default(omit) }}"
    https_proxy: "{{ zabbix_https_proxy | default(None) | default(omit) }}"
  register: zabbix_java_gateway_install
  until: zabbix_java_gateway_install is succeeded
  become: true
  tags:
    - install

- name: "Debian | Make sure Zabbix Java Gateway is not yet running"
  systemd:
    name: zabbix-java-gateway
    state: stopped
    enabled: true
    daemon_reload: true
  when:
    - zabbix_java_gateway_install.changed
  tags:
    - service
