---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_facts['os_family'] }}.yml"
  tags:
    - always

- name: Determine Latest Supported Zabbix Version
  ansible.builtin.set_fact:
    zabbix_javagateway_version: "{{ zabbix_valid_javagateway_versions[ansible_facts['distribution_major_version']][0] | default(7.2) }}"
  when: zabbix_javagateway_version is not defined
  tags:
    - always

- name: Check that version is supported
  when: zabbix_javagateway_version_check | bool
  ansible.builtin.assert:
    that:
      - "{{ zabbix_javagateway_version|float in zabbix_valid_javagateway_versions[ansible_facts['distribution_major_version']] }}"
    fail_msg: Zabbix version {{ zabbix_javagateway_version }} is not supported on {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_major_version'] }}
  tags:
    - always

- name: Install Repository
  ansible.builtin.include_role:
    name: community.zabbix.zabbix_repo
  vars:
    zabbix_repo_version: "{{ zabbix_javagateway_version }}"
    zabbix_repo_package: "zabbix-java-gateway"
  when: zabbix_manage_repo | default(true)

# SLES 15 comes with openjdk-11 by default.
# In order for the zabbix-java-gateway to work, we need to install openjdk-17.
- name: "Suse | Install openjdk-{{ zabbix_javagateway_openjdk_version }}"
  when: ansible_facts['os_family'] == 'Suse'
  ansible.builtin.package:
    name:
      - java-{{ zabbix_javagateway_openjdk_version }}-openjdk-headless
      - java-{{ zabbix_javagateway_openjdk_version }}-openjdk
    state: "{{ zabbix_javagateway_package_state }}"
  environment:
    http_proxy: "{{ zabbix_http_proxy | default('') }}"
    https_proxy: "{{ zabbix_https_proxy | default('') }}"
  register: _zabbix_javagateway_openjdk
  until: _zabbix_javagateway_openjdk is succeeded
  become: true
  tags:
    - install

- name: Install zabbix-java-gateway
  ansible.builtin.package:
    name: zabbix-java-gateway
    state: "{{ zabbix_javagateway_package_state }}"
    update_cache: true
    disablerepo: "{{ zabbix_javagateway_disable_repo | default(_zabbix_javagateway_disable_repo | default(omit)) }}"
    install_recommends: "{{ zabbix_javagateway_install_recommends | default(_zabbix_javagateway_install_recommends | default(omit)) }}"
  environment:
    http_proxy: "{{ zabbix_http_proxy | default('') }}"
    https_proxy: "{{ zabbix_https_proxy | default('') }}"
  register: _zabbix_javagateway_install
  until: _zabbix_javagateway_install is succeeded
  become: true
  tags:
    - install

- name: "Configure zabbix-proxy"
  ansible.builtin.template:
    src: zabbix_java_gateway.conf.j2
    dest: /etc/zabbix/zabbix_java_gateway.conf
    owner: zabbix
    group: zabbix
    mode: "{{ zabbix_java_gateway_conf_mode }}"
  become: true
  notify:
    - zabbix-java-gateway restarted
  tags:
    - config

- name: "Make sure Zabbix Java Gateway is running"
  ansible.builtin.systemd:
    name: zabbix-java-gateway
    state: started
    enabled: true
    daemon_reload: true
  become: true
  tags:
    - service
