---
# Tasks specific for OpenSuse Systems

- name: "Include Zabbix gpg ids"
  include_vars: zabbix.yml

- name: "Install zypper repo dependency"
  community.general.zypper:
    name:
      - python-xml
      - "{{ suse[ansible_distribution][zabbix_agent_distribution_major_version]['python_libxml2_package'] }}"
    state: present
  environment:
    http_proxy: "{{ zabbix_http_proxy | default(None) | default(omit) }}"
    https_proxy: "{{ zabbix_https_proxy | default(None) | default(omit) }}"
  become: true
  register: zabbix_agent_package_dependency
  until: zabbix_agent_package_dependency is succeeded

- name: "Suse | Install basic repo file"
  community.general.zypper_repository:
    repo: "{{ suse[ansible_distribution][zabbix_agent_distribution_major_version]['url'] }}"
    name: "{{ suse[ansible_distribution][zabbix_agent_distribution_major_version]['name'] }}"
    state: present
  environment:
    http_proxy: "{{ zabbix_http_proxy | default(None) | default(omit) }}"
    https_proxy: "{{ zabbix_https_proxy | default(None) | default(omit) }}"
  when:
    - zabbix_repo == "zabbix"
  become: true
  tags:
    - zabbix-agent
    - init

- name: "Only install the Zabbix Agent"
  set_fact:
    zabbix_agent_packages:
      - "{{ zabbix_agent_package }}"
  when:
    - zabbix_agent_install_agent_only

- name: "Suse | Install zabbix-agent"
  community.general.zypper:
    name: "{{ zabbix_agent_packages }}"
    state: "{{ zabbix_agent_package_state }}"
    disable_gpg_check: true
  environment:
    http_proxy: "{{ zabbix_http_proxy | default(None) | default(omit) }}"
    https_proxy: "{{ zabbix_https_proxy | default(None) | default(omit) }}"
  register: zabbix_agent_package_installed
  until: zabbix_agent_package_installed is succeeded
  become: true
  tags:
    - zabbix-agent
    - init
