---
- name: Converge
  hosts: all
  environment:
    http_proxy: "{{ zabbix_http_proxy }}"
    https_proxy: "{{ zabbix_https_proxy }}"
    no_proxy: "{{ zabbix_no_proxy }}"
  roles:
    - role: zabbix_agent
