---
_apache_user: www-data
_apache_group: www-data
_apache_log: apache2
_apache_service: apache2
_apache_vhost_location: /etc/apache2/sites-available/zabbix.conf

_php_fpm_dir: /etc/php/{{ zabbix_web_php_installed_version }}/fpm/pool.d
_php_fpm_session: /tmp
_zabbix_php_fpm_listen: /run/php/zabbix.sock
_zabbix_php_fpm_mode: "0666"
_zabbix_php_fpm_allowed_clients: 127.0.0.1


_nginx_user: www-data
_nginx_group: www-data
_nginx_vhost_location: /etc/nginx/conf.d/zabbix.conf
_nginx_log_path: /var/log/nginx
_nginx_service: nginx
_nginx_tls_crt: /etc/ssl/certs/ssl-cert-snakeoil.pem
_nginx_tls_key: /etc/ssl/private/ssl-cert-snakeoil.key
_nginx_tls_dhparam: /etc/ssl/private/dhparams.pem

zabbix_valid_web_versions:
  # Debian
  "12":
    - 7.2
    - 7.0
    - 6.4
    - 6.0
  "11":
    - 6.4
    - 6.0
  # Ubuntu
  "24":
    - 7.2
    - 7.0
    - 6.4
    - 6.0
  "22":
    - 7.2
    - 7.0
    - 6.4
    - 6.0
  "20":
    - 6.4
    - 6.0

_zabbix_web_package: zabbix-frontend-php
_zabbix_web_apache_packages:
  - zabbix-apache-conf
_zabbix_web_apache_php_dependencies:
  - "libapache2-mod-php{{ zabbix_web_php_installed_version }}"
  - "php{{ zabbix_web_php_installed_version }}-{{ zabbix_server_database }}"
_zabbix_web_nginx_packages:
  - zabbix-nginx-conf
_zabbix_web_nginx_php_dependencies:
  - "php{{ zabbix_web_php_installed_version }}-{{ zabbix_server_database }}"
