---
sign_keys:
  "64":
    bullseye:
      sign_key: E709712C
    buster:
      sign_key: E709712C
    stretch:
      sign_key: E709712C
    focal:
      sign_key: E709712C
    bionic:
      sign_key: E709712C
    xenial:
      sign_key: E709712C
    trusty:
      sign_key: E709712C
    jammy:
      sign_key: E709712C
  "62":
    bullseye:
      sign_key: E709712C
    buster:
      sign_key: E709712C
    stretch:
      sign_key: E709712C
    focal:
      sign_key: E709712C
    bionic:
      sign_key: E709712C
    xenial:
      sign_key: E709712C
    trusty:
      sign_key: E709712C
    jammy:
      sign_key: E709712C
  "60":
    bullseye:
      sign_key: E709712C
    buster:
      sign_key: E709712C
    stretch:
      sign_key: E709712C
    focal:
      sign_key: E709712C
    bionic:
      sign_key: E709712C
    xenial:
      sign_key: E709712C
    trusty:
      sign_key: E709712C
    jammy:
      sign_key: E709712C
