---
# defaults file for zabbix_agent

zabbix_agent2: false
# zabbix_agent_version: 6.0
zabbix_agent_version_minor: "*"
zabbix_version: "{{ zabbix_agent_version }}"
zabbix_version_patch: 0
zabbix_repo: zabbix
zabbix_agent_package_remove: false
zabbix_agent_package: zabbix-agent
zabbix_sender_package: zabbix-sender
zabbix_get_package: zabbix-get
zabbix_agent_package_state: present
zabbix_agent_server:
zabbix_agent_serveractive:
zabbix_agent2_server: "{{ zabbix_agent_server }}"
zabbix_agent2_serveractive: "{{ zabbix_agent_serveractive }}"
zabbix_selinux: false
zabbix_agent_src_reinstall: false
zabbix_agent_apt_priority:
zabbix_agent_conf_mode: "0644"
zabbix_agent_dont_detect_ip: false
zabbix_agent_allow_key: []
zabbix_agent_deny_key: []
zabbix_agent2_allow_key: "{{ zabbix_agent_allow_key }}"
zabbix_agent2_deny_key: "{{ zabbix_agent_deny_key }}"

# Selinux related vars
selinux_allow_zabbix_run_sudo: false

zabbix_agent_install_agent_only: false
zabbix_agent_packages:
  - "{{ zabbix_agent_package }}"
  - "{{ zabbix_sender_package }}"
  - "{{ zabbix_get_package }}"

# Zabbix role related vars
zabbix_install_pip_packages: true
zabbix_apt_force_apt_get: true
zabbix_apt_install_recommends: false

# Override Ansible specific facts
zabbix_agent_distribution_major_version: "{{ ansible_distribution_major_version }}"
zabbix_agent_distribution_release: "{{ ansible_distribution_release }}"
zabbix_agent_os_family: "{{ ansible_os_family }}"
zabbix_repo_yum_gpgcheck: 0
zabbix_repo_yum_schema: https
zabbix_repo_yum_disabled: "*"
zabbix_repo_yum_enabled: []
zabbix_repo_yum:
  - name: zabbix
    description: Zabbix Official Repository - $basearch
    baseurl: "{{ zabbix_repo_yum_schema }}://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/{{ zabbix_agent_distribution_major_version }}/$basearch/"
    mode: "0644"
    gpgcheck: "{{ zabbix_repo_yum_gpgcheck }}"
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX
    state: present
  - name: zabbix-non-supported
    description: Zabbix Official Repository non-supported - $basearch
    baseurl: "{{ zabbix_repo_yum_schema }}://repo.zabbix.com/non-supported/rhel/{{ zabbix_agent_distribution_major_version }}/$basearch/"
    mode: "0644"
    gpgcheck: "{{ zabbix_repo_yum_gpgcheck }}"
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX
    state: present
  - name: zabbix-agent2-plugins
    description: Zabbix Official Repository (Agent2 Plugins) - $basearch
    baseurl: "{{ zabbix_repo_yum_schema }}://repo.zabbix.com/zabbix-agent2-plugins/1/rhel/{{ zabbix_agent_distribution_major_version }}/$basearch/"
    mode: "0644"
    gpgcheck: "{{ zabbix_repo_yum_gpgcheck }}"
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX
    state: present

# Zabbix API stuff
zabbix_validate_certs: true # Will be deprecated in 2.0.0
zabbix_api_validate_certs: "{{ zabbix_validate_certs }}"
zabbix_agent_server_url: http://localhost # Will be deprecated in 2.0.0
zabbix_url: "{{ zabbix_agent_server_url }}" # Will be deprecated in 2.0.0
zabbix_api_server_url: "{{ zabbix_agent_server_url }}"
zabbix_api_server_host: "{{ zabbix_api_server_url | urlsplit('hostname') }}"
zabbix_api_port_from_url: "{{ zabbix_api_server_port | default(zabbix_api_server_url | urlsplit('port')) }}"
zabbix_api_scheme_from_url: "{{ zabbix_api_server_url | urlsplit('scheme') }}"
zabbix_api_port_from_shema: "{{ (zabbix_api_scheme_from_url == 'https') | ternary(443, 80) }}"
# zabbix_http_user: admin                          # Will be deprecated in 2.0.0
# zabbix_http_password: admin                      # Will be deprecated in 2.0.0
# zabbix_api_http_user: admin
# zabbix_api_http_password: admin
zabbix_api_user: Admin # Will be deprecated in 2.0.0
zabbix_api_pass: !unsafe zabbix # Will be deprecated in 2.0.0
zabbix_api_login_user: "{{ zabbix_api_user }}"
zabbix_api_login_pass: "{{ zabbix_api_pass }}"
ansible_httpapi_pass: "{{ zabbix_api_login_pass }}"
ansible_httpapi_port: "{{ (zabbix_api_port_from_url == '') | ternary(zabbix_api_port_from_shema, zabbix_api_port_from_url) }}"
ansible_httpapi_use_ssl: "{{ zabbix_api_use_ssl | default((zabbix_api_scheme_from_url == 'https') | ternary(true, false)) }}"
ansible_httpapi_validate_certs: "{{ zabbix_api_validate_certs }}"
zabbix_api_create_hostgroup: false
zabbix_api_create_hosts: false
zabbix_api_timeout: 30
zabbix_create_hostgroup: present # or absent      # Will be deprecated in 2.0.0
zabbix_agent_hostgroups_state: "{{ zabbix_create_hostgroup }}"
zabbix_create_host: present # or absent      # Will be deprecated in 2.0.0
zabbix_agent_host_state: "{{ zabbix_create_host }}"
zabbix_update_host: true # Will be deprecated in 2.0.0
zabbix_agent_host_update: "{{ zabbix_update_host }}"
zabbix_host_status: enabled # or disabled
zabbix_proxy: null # Will be deprecated in 2.0.0
zabbix_agent_proxy: "{{ zabbix_proxy }}"
zabbix_inventory_mode: disabled # Will be deprecated in 2.0.0
zabbix_agent_inventory_mode: "{{ zabbix_inventory_mode }}"
zabbix_useuip: 1
zabbix_host_groups:
  - Linux servers
zabbix_link_templates: # Will be deprecated in 2.0.0
  - Template Linux by Zabbix agent
zabbix_agent_link_templates: "{{ zabbix_link_templates }}"

zabbix_agent_interfaces:
  - type: 1
    main: 1
    useip: "{{ zabbix_useuip }}"
    ip: "{{ zabbix_agent_ip }}"
    dns: "{{ ansible_fqdn }}"
    port: "{{ (zabbix_agent2 == True) | ternary(zabbix_agent2_listenport, zabbix_agent_listenport) }}"

zabbix_agent_firewall_enable: false
zabbix_agent_firewalld_enable: false
zabbix_agent_firewalld_source: "{{ zabbix_agent_server }}"
zabbix_agent_firewall_action: insert
zabbix_agent_firewall_chain: INPUT

# By default, a null zone will trigger the use of the default zone on the remote host
zabbix_agent_firewalld_zone:
# Zabbix configuration variables
zabbix_agent_pidfile: /var/run/zabbix/zabbix_agentd.pid
zabbix_agent_logtype: file
zabbix_agent_logfile: /var/log/zabbix/zabbix_agentd.log
zabbix_agent_logfilesize: 100
zabbix_agent_debuglevel: 3
zabbix_agent_sourceip:
zabbix_agent_enableremotecommands: 0
zabbix_agent_allowkeys:
zabbix_agent_denykeys:
zabbix_agent_logremotecommands: 0
zabbix_agent_listenport: 10050
zabbix_agent_jmx_listenport:
zabbix_agent_listeninterface:
zabbix_agent_listenip:
zabbix_agent_startagents: 3
zabbix_agent_hostname: "{{ inventory_hostname }}"
zabbix_agent_hostnameitem:
zabbix_agent_hostmetadata:
zabbix_agent_hostmetadataitem:
zabbix_agent_refreshactivechecks: 120
zabbix_agent_buffersend: 5
zabbix_agent_buffersize: 100
zabbix_agent_maxlinespersecond: 100
zabbix_agent_allowroot: 0
zabbix_agent_zabbix_alias:
zabbix_agent_timeout: 3
zabbix_agent_include: /etc/zabbix/zabbix_agentd.d
zabbix_agent_include_pattern:
zabbix_agent_include_mode: "0750"
zabbix_agent_unsafeuserparameters: 0
zabbix_agent_userparameters: []
zabbix_agent_userparameters_templates_src: "userparameters"
zabbix_agent_userparameters_scripts_src: "scripts"
zabbix_agent_custom_scripts: false
zabbix_agent_loadmodulepath: ${libdir}/modules
zabbix_agent_loadmodule:
zabbix_agent_become_on_localhost: true
zabbix_agent_description:
zabbix_agent_inventory_zabbix: {}
zabbix_agent_heartbeatfrequency: 60
zabbix_macros: [] # Will be deprecated in 2.0.0
zabbix_agent_macros: "{{ zabbix_macros }}"
zabbix_agent_tags: []
zabbix_agent_chassis: false

# TLS settings
zabbix_agent_tlsconnect:
zabbix_agent_tlsaccept:
zabbix_agent_tlscafile:
zabbix_agent_tlscrlfile:
zabbix_agent_tlsservercertissuer:
zabbix_agent_tlsservercertsubject:
zabbix_agent_tls_subject: "{{ zabbix_agent_tlsservercertsubject }}" # FIXME this is not correct and should be removed with 2.0.0, here only to prevent regression
zabbix_agent_tlscertfile:
zabbix_agent_tlskeyfile:
zabbix_agent_tlspskidentity:
zabbix_agent_tlspsk_auto: false

zabbix_agent_tls_config:
  unencrypted: "1"
  psk: "2"
  cert: "4"

# IPMI settings
zabbix_agent_ipmi_authtype: 2
zabbix_agent_ipmi_password:
zabbix_agent_ipmi_privilege: 2
zabbix_agent_ipmi_username:

# Zabbix Agent2
zabbix_agent2_pidfile: /var/run/zabbix/zabbix_agent2.pid
zabbix_agent2_logfile: /var/log/zabbix/zabbix_agent2.log
zabbix_agent2_logtype: file
zabbix_agent2_statusport: 9999
zabbix_agent2_include: /etc/zabbix/zabbix_agent2.d
zabbix_agent2_include_pattern:
zabbix_agent2_logfilesize: 100
zabbix_agent2_debuglevel: 3
zabbix_agent2_sourceip:
zabbix_agent2_listenport: 10050
zabbix_agent2_listenip:
zabbix_agent2_hostname: "{{ inventory_hostname }}"
zabbix_agent2_hostnameitem:
zabbix_agent2_hostmetadata:
zabbix_agent2_hostmetadataitem:
zabbix_agent2_hostinterface:
zabbix_agent2_hostinterfaceitem:
zabbix_agent2_enablepersistentbuffer: 0
zabbix_agent2_persistentbufferperiod: 1h
zabbix_agent2_persistentbufferfile:
zabbix_agent2_refreshactivechecks: 120
zabbix_agent2_buffersend: 5
zabbix_agent2_buffersize: 100
zabbix_agent2_zabbix_alias:
zabbix_agent2_timeout: 3
zabbix_agent2_include_mode: "0750"
zabbix_agent2_unsafeuserparameters: 0
zabbix_agent2_controlsocket: /tmp/agent.sock
zabbix_agent2_plugins: []

# Zabbix Agent2 TLS settings
zabbix_agent2_tlsconnect:
zabbix_agent2_tlsaccept:
zabbix_agent2_tlscafile:
zabbix_agent2_tlscrlfile:
zabbix_agent2_tlsservercertissuer:
zabbix_agent2_tlsservercertsubject:
zabbix_agent2_tls_subject: "{{ zabbix_agent2_tlsservercertsubject }}" # FIXME this is not correct and should be removed with 2.0.0, here only to prevent regression
zabbix_agent2_tlscertfile:
zabbix_agent2_tlskeyfile:
zabbix_agent2_tlspskidentity:
zabbix_agent2_tlspsk_auto: false

# Windows/macOS Related
zabbix_version_long: 5.2.4

# Windows Related
zabbix_win_package: zabbix_agent-{{ zabbix_version_long }}-windows-amd64-openssl.zip
zabbix2_win_package: zabbix_agent2-{{ zabbix_version_long }}-windows-amd64-openssl-static.zip
zabbix_win_download_url: https://cdn.zabbix.com/zabbix/binaries/stable
zabbix_win_download_link: "{{ zabbix_win_download_url }}/{{ zabbix_version_long | regex_search('^\\d+\\.\\d+') }}/{{ zabbix_version_long }}/{{ zabbix_win_package }}"
zabbix2_win_download_link: "{{ zabbix_win_download_url }}/{{ zabbix_version_long | regex_search('^\\d+\\.\\d+') }}/{{ zabbix_version_long }}/{{ zabbix2_win_package }}"
zabbix_win_install_dir: 'C:\Zabbix'
zabbix_win_install_dir_conf: '{{ zabbix_win_install_dir }}\\conf'
zabbix_win_install_dir_bin: '{{ zabbix_win_install_dir }}\\bin'
zabbix_agent_win_logfile: "{{ zabbix_win_install_dir }}\\zabbix_agentd.log"
zabbix_agent_win_include: "{{ zabbix_win_install_dir }}\\zabbix_agent.d\\"
zabbix_agent2_win_logfile: "{{ zabbix_win_install_dir }}\\zabbix_agent2.log"
zabbix_agent_win_svc_recovery: true
zabbix_win_firewall_management: true

# macOS Related
zabbix_mac_package: zabbix_agent-{{ zabbix_version_long }}-macos-amd64-openssl.pkg
zabbix_mac_download_url: https://cdn.zabbix.com/zabbix/binaries/stable
zabbix_mac_download_link: "{{ zabbix_mac_download_url }}/{{ zabbix_agent_version }}/{{ zabbix_version_long }}/{{ zabbix_mac_package }}"

# Zabbix Agent Docker facts
zabbix_agent_docker: false
zabbix_agent_docker_state: started
zabbix_agent_docker_name: zabbix-agent
zabbix_agent_docker_image: "zabbix/zabbix-agent"
zabbix_agent_docker_image_tag: "ubuntu-{{ zabbix_version }}.{{ zabbix_version_patch }}"
zabbix_agent_docker_user_gid: 101
zabbix_agent_docker_user_uid: 101
zabbix_agent_docker_network_mode: host
zabbix_agent_docker_restart_policy: unless-stopped
zabbix_agent_docker_privileged: false
zabbix_agent_docker_ports:
  - 10050:10050
zabbix_agent_docker_security_opts:
  - apparmor:unconfined
zabbix_agent_docker_volumes:
  - /etc/zabbix/zabbix_agentd.d:{{ zabbix_agent_include }}
  - /:/hostfs:ro
  - /etc:/hostfs/etc:ro
  - /proc:/hostfs/proc:ro
  - /sys:/hostfs/sys:ro
  - /var/run:/var/run
zabbix_agent_docker_env:
  ZBX_HOSTNAME: "{{ zabbix_agent_hostname }}"
  ZBX_SERVER_HOST: "{{ zabbix_agent_server }}"
  ZBX_PASSIVE_ALLOW: "{{ zabbix_agent_serverpassive_allow | default(omit) }}"
  ZBX_PASSIVESERVERS: "{{ zabbix_agent_serverpassive | default(omit) }}"
  ZBX_ACTIVE_ALLOW: "{{ zabbix_agent_serveractive_allow | default(omit) }}"
  ZBX_LOADMODULE: "{{ zabbix_agent_loadmodule | default(omit) }}"
  ZBX_DEBUGLEVEL: "{{ zabbix_agent_debuglevel }}"
  ZBX_TIMEOUT: "{{ zabbix_agent_timeout }}"
  ZBX_SOURCEIP: "{{ zabbix_agent_sourceip | default(omit) }}"
  ZBX_ENABLEREMOTECOMMANDS: "{{ zabbix_agent_enableremotecommands | default(omit) }}"
  ZBX_LOGREMOTECOMMANDS: "{{ zabbix_agent_logremotecommands | default(omit) }}"
  ZBX_STARTAGENTS: "{{ zabbix_agent_startagents | default(omit) }}"
  ZBX_HOSTNAMEITEM: "{{ zabbix_agent_hostnameitem | default(omit) }}"
  ZBX_METADATA: "{{ zabbix_agent_hostmetadata | default(omit) }}"
  ZBX_METADATAITEM: "{{ zabbix_agent_hostmetadataitem | default(omit) }}"
  ZBX_REFRESHACTIVECHECKS: "{{ zabbix_agent_refreshactivechecks | default(omit) }}"
  ZBX_BUFFERSEND: "{{ zabbix_agent_buffersend | default(omit) }}"
  ZBX_BUFFERSIZE: "{{ zabbix_agent_buffersize | default(omit) }}"
  ZBX_MAXLINESPERSECOND: "{{ zabbix_agent_maxlinespersecond | default(omit) }}"
  ZBX_LISTENIP: "{{ zabbix_agent_listenip }}"
  ZBX_UNSAFEUSERPARAMETERS: "{{ zabbix_agent_unsafeuserparameters | default(omit) }}"
  ZBX_TLSCONNECT: "{{ zabbix_agent_tlsconnect | default(omit) }}"
  ZBX_TLSACCEPT: "{{ zabbix_agent_tlsaccept | default(omit) }}"
  ZBX_TLSCAFILE: "{{ zabbix_agent_tlscafile | default(omit) }}"
  ZBX_TLSCRLFILE: "{{ zabbix_agent_tlscrlfile | default(omit) }}"
  ZBX_TLSSERVERCERTISSUER: "{{ zabbix_agent_tlsservercertissuer | default(omit) }}"
  ZBX_TLSSERVERCERTSUBJECT: "{{ zabbix_agent_tlsservercertsubject | default(omit) }}"
  ZBX_TLSCERTFILE: "{{ zabbix_agent_tlscertfile | default(omit) }}"
  ZBX_TLSKEYFILE: "{{ zabbix_agent_tlskeyfile | default(omit) }}"
  ZBX_TLSPSKIDENTITY: "{{ zabbix_agent_tlspskidentity | default(omit) }}"
