---
- name: restart zabbix-agent
  ansible.builtin.service:
    name: "{{ zabbix_agent_service }}"
    state: restarted
    enabled: true
  become: true
  when:
    - not zabbix_agent_docker
    - ansible_os_family != "Windows" and ansible_os_family != "Darwin"

- name: firewalld-reload
  ansible.builtin.command: "firewall-cmd --reload"
  become: true
  when:
    - ansible_facts.services["firewalld"] is defined
    - ansible_facts.services["firewalld"].state == "running"

- name: restart win zabbix agent
  ansible.windows.win_service:
    name: "{{ zabbix_agent_win_service }}"
    state: restarted
  when:
    - ansible_facts['os_family'] == "Windows"

- name: restart mac zabbix agent
  ansible.builtin.command: "launchctl kickstart -k system/{{ zabbix_agent_service }}"
  become: true
  when:
    - not zabbix_agent_docker
    - ansible_os_family == "Darwin"
