zabbix_valid_javagateway_versions:
  # Debian
  "11":
    - 6.2
    - 6.0
    - 5.0
  "10":
    - 6.2
    - 6.0
    - 5.0
  # Ubuntu
  "22":
    - 6.2
    - 6.0
    - 5.0
  "20":
    - 6.2
    - 6.0
    - 5.0
  "18":
    - 6.2
    - 6.0
    - 5.0
