---
zabbix_valid_javagateway_versions:
  "10":
    - 7.4
  "9":
    - 7.4
    - 7.2
    - 7.0
    - 6.0
  "8":
    - 7.4
    - 7.2
    - 7.0
    - 6.0
  "7":
    - 6.0

_zabbix_javagateway_disable_repo:
  - epel
