---
name: "community.zabbix.zabbix_javagateway"
on:
  push:
    paths:
      - "roles/zabbix_javagateway/**"
      - "molecule/zabbix_javagateway/**"
      - "molecule/requirements.txt"
      - ".github/workflows/javagateway.yml"
      - "roles/zabbix_repo/**"
      - "molecule/zabbix_repo/**"
      - ".github/workflows/repo.yml"
  pull_request:
    paths:
      - "roles/zabbix_javagateway/**"
      - "molecule/zabbix_javagateway/**"
      - "molecule/requirements.txt"
      - ".github/workflows/javagateway.yml"
      - "roles/zabbix_repo/**"
      - "molecule/zabbix_repo/**"
      - ".github/workflows/repo.yml"
jobs:
  molecule:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        container:
          - image: rockylinux9
          - image: rockylinux8
            ansible_core: ansible-core<2.17
          - image: ubuntu2404
          - image: ubuntu2204
          - image: debian12
          - image: debian11
          - image: opensuseleap15
            ansible_core: ansible-core<2.17
        version:
          - v74
          - v72
          - v70
          - v60
        collection_role:
          - zabbix_javagateway
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install latest pip
        run: python -m pip install --upgrade pip

      - name: Install specific version ansible-core
        if: matrix.container.ansible_core != null
        run: pip install "${{ matrix.container.ansible_core }}"

      - name: Install dependencies
        run: pip install -r molecule/requirements.txt

      - name: Build the collection
        run: |
          # Pin versions to speed up CI
          sed -i 's/ansible\.windows:\s*"\*"/ansible.windows: "2.8.0"/' galaxy.yml
          sed -i 's/ansible\.netcommon:\s*"\*"/ansible.netcommon: "7.2.0"/' galaxy.yml
          sed -i 's/ansible\.posix:\s*"\*"/ansible.posix: "2.0.0"/' galaxy.yml
          sed -i 's/community\.general:\s*"\*"/community.general: "10.5.0"/' galaxy.yml
          sed -i 's/community\.mysql:\s*"\*"/community.mysql: "3.13.0"/' galaxy.yml
          sed -i 's/community\.postgresql:\s*"\*"/community.postgresql: "3.12.0"/' galaxy.yml

          collection_file=$( basename $(ansible-galaxy collection build -f | awk -F" " '{print $NF}'))
          echo "COLLECTION_FILE=$collection_file" >> $GITHUB_ENV

      - name: Install the collection
        run: ansible-galaxy collection install -vvvv $COLLECTION_FILE

      - name: Run role tests
        run: >-
          MY_MOLECULE_CONTAINER=${{ matrix.container.image }}
          MY_MOLECULE_IMAGE=${{ matrix.container.image }}
          MY_MOLECULE_VERSION=${{ matrix.version }}
          MY_MOLECULE_DOCKER_COMMAND=${{ matrix.command }}
          molecule test -s ${{ matrix.collection_role }}
